server:
  port: 8888

#management:
#  context-path: /admin
#  endpoints:
#    web:
#      base-path: ${management.context-path}

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web.filter: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
#    statusPageUrlPath: /admin/info
#    healthCheckUrlPath: /admin/health

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:breath-project/config-repo.git
          basedir: target/config

---
spring:
  profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
