server:
  port: 8888

management:
  #  context-path: /admin
  endpoints:
    web:
      #      base-path: ${management.context-path}
      exposure:
        #                include: refresh
        include: "*"

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web.filter: 'DEBUG'

#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 10
#    statusPageUrlPath: /admin/info
#    healthCheckUrlPath: /admin/health

spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
        - type: git
          uri: git@github.com:breath-project/config-repo.git
          basedir: target/config
        - type: native

---
spring:
  profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
